//LAYOUT ES PARA ESTRUCTURA HTML


import { Inter } from 'next/font/google'
import './styles/globals.css'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Spotify',
  description: 'Generated by Clara Salgado die beste',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}